### ISSUE TITLE
CUDA error: invalid argument

### ISSUE THREAD

**Issue by JohnneyTexas** [Comfy-Org/ComfyUI#11152]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

When I used PuLID (PuLID_Flux_II), this error occurred.

However, this phenomenon isn't reliably reproducible, which is causing me trouble.

1.  Sometimes image generation proceeds normally without the error occurring
2.  Sometimes, despite the error appearing, repeated attempts eventually succeed in generating an image
3.  Sometimes disabling the node allows normal image generation
4.  Sometimes disabling the node does not resolve the issue

If this is a clear bug, I would appreciate it being fixed promptly. However, if there is a way I can resolve this myself without waiting for a fix, please do let me know.

The operating environment is as follows:
Python: 3.10.11 (within Stability Marix)
Pytorch version: 2.9.1+cu128 (even when I set it to cu130, it would revert to cu128 for some reason upon update)
OS: Windows 10
VRAM: 12GB
DRAM: 64GB

### Logs

```powershell
!!! Exception during processing !!! CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 291, in process_inputs
    result = f(**inputs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1538, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1505, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\sample.py", line 60, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 1163, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 1053, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 1035, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 113, in execute
    return self.wrappers[self.idx](self, *args, **kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_PuLID_Flux_ll\pulidflux.py", line 625, in pulid_outer_sample_wrappers_with_override
    out = wrapper_executor(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, **kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 105, in __call__
    return new_executor.execute(*args, **kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 984, in outer_sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds, self.model_options)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\sampler_helpers.py", line 130, in prepare_sampling
    return executor.execute(model, noise_shape, conds, model_options=model_options)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\sampler_helpers.py", line 138, in _prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required + inference_memory, minimum_memory_required=minimum_memory_required + inference_memory)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 701, in load_models_gpu
    loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 506, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 536, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_patcher.py", line 952, in partially_load
    self.partially_unload(self.offload_device, -extra_memory, force_patch_weights=force_patch_weights)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_patcher.py", line 901, in partially_unload
    m.to(device_to)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1371, in to
    return self._apply(convert)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\ops.py", line 639, in _apply
    self.register_parameter(key, torch.nn.Parameter(fn(param), requires_grad=False))
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1357, in convert
    return t.to(
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 205, in __torch_dispatch__
    return _GENERIC_UTILS[func](func, args, kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 321, in generic_to_dtype_layout
    return _handle_device_transfer(
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 272, in _handle_device_transfer
    new_q_data = qt._qdata.to(device=target_device)
torch.AcceleratorError: CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by rattus128** [comment]
Cuda einval on partially unload can be a product of using an old and incompatible version of GGUF loaders. --disable-pinned-memory works around but can cost you a lot of performance. Make sure you are on the latest version of ComfyUi-GGUF if doing GGUF anywhere in the flow.

If it's not GGUF we need full information on the bug as these are hard to pinpoint. A full workflow and paste the entire log at least starting from "got prompt".

**Comment by jasonblack23** [comment]
Not the OP but I had the same error. I have been unable to reproduce the error using a different GGUF Loader, in my case the Unet Loader (GGUF) custom node works just fine.

The problem loader is:
name: loadergguf
version: 2.6.5
cnr_id: gguf
ue properties says: {"widget_ue_connectable":{},"input_ue_unconnectable":{},"version":"7.4.1"}

Is there a more detailed id I can report?

Update. The default loader that appears highlighted at the top of the list when clicking and searching for GGUF Loaders, immediately returned an error too. Version 2.7.5 looks like the default?

**Comment by JohnneyTexas** [comment]
> Cuda einval on partially unload can be a product of using an old and incompatible version of GGUF loaders. --disable-pinned-memory works around but can cost you a lot of performance. Make sure you are on the latest version of ComfyUi-GGUF if doing GGUF anywhere in the flow.
> 
> If it's not GGUF we need full information on the bug as these are hard to pinpoint. A full workflow and paste the entire log at least starting from "got prompt".


Thank you. And I apologise for the lack of explanation.
The error occurs when processing moves from sampling to VAE decoding. That is, the sampling itself completes normally even when the error occurs. Furthermore, in the current situation, once an error occurs, it persists unless Comfy is restarted; disabling the node or change the model does not resolve it.
Also, gguf is not being used.

In this test, after restarting Comfy following an error, it none triggered the error again, and time constraints prevented thorough testing. However, it might be causing instability where the error occurs or completes normally depending on memory usage.

In this test, the error occurred with the combination CFG=1, Guidance=3.5, euler + simple, with Negative Prompt. Yet, even with the same combination after restarting, it failed to reproduce and completed normally.
Furthermore, whether using CFG>1.0 (with Negative Prompt) or CFG=1 (without Negative Prompt), errors sometimes occur and sometimes do not in either case.
The model used in this test was the FP8 Full Model(*), but during normal usage, there is no particular difference in error occurrence whether using FP16 or FP8, or whether using the Full Model or the Pruned Model.

* https://civitai.com/models/1032613?modelVersionId=1158144

-----

[On Error]

got prompt 10:39:48
Requested to load Flux
loaded partially; 8480.79 MB usable, 8372.35 MB loaded, 2980.68 MB offloaded, 108.02 MB buffer reserved, lowvram patches: 0
Unloaded partially: 765.10 MB freed, 324.06 MB remains loaded, 36.00 MB buffer reserved, lowvram patches: 0
100%|██████████| 30/30 [02:12<00:00,  4.42s/it]
Requested to load AutoencodingEngine
!!! Exception during processing !!! CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 291, in process_inputs
    result = f(**inputs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 298, in decode
    images = vae.decode(samples["samples"])
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\sd.py", line 774, in decode
    model_management.load_models_gpu([self.patcher], memory_required=memory_used, force_full_load=self.disable_offload)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 671, in load_models_gpu
    free_memory(total_memory_required[device] * 1.1 + extra_mem, device)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 603, in free_memory
    if current_loaded_models[i].model_unload(memory_to_free):
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 526, in model_unload
    freed = self.model.partially_unload(self.model.offload_device, memory_to_free)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_patcher.py", line 904, in partially_unload
    m.to(device_to)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1371, in to
    return self._apply(convert)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\ops.py", line 639, in _apply
    self.register_parameter(key, torch.nn.Parameter(fn(param), requires_grad=False))
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1357, in convert
    return t.to(
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 205, in __torch_dispatch__
    return _GENERIC_UTILS[func](func, args, kwargs)
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 321, in generic_to_dtype_layout
    return _handle_device_transfer(
  File "Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\comfy\quant_ops.py", line 272, in _handle_device_transfer
    new_q_data = qt._qdata.to(device=target_device)
torch.AcceleratorError: CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

-----

[On success-the first time]

got prompt 10:57:52
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
[MultiGPU Core Patching] text_encoder_device_patched returning device: cpu (current_text_encoder_device=cpu)
Requested to load FluxClipModel_
loaded completely; 95367431640625005117571072.00 MB usable, 5013.38 MB loaded, full load: True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float32
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\models\insightface\models\antelopev2\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\models\insightface\models\antelopev2\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\models\insightface\models\antelopev2\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\models\insightface\models\antelopev2\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: Z:\WorkSpace\StabilityMatrix\Data\Packages\ComfyUI\models\insightface\models\antelopev2\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
Loaded EVA02-CLIP-L-14-336 model config.
Shape of rope freq: torch.Size([576, 64])
Loading pretrained EVA02-CLIP-L-14-336 weights (eva_clip).
incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 
'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
Loading PuLID-Flux model.
Found quantization metadata version 1
Detected mixed precision quantization
Using mixed precision operations
model weight dtype torch.bfloat16, manual cast: torch.bfloat16
model_type FLUX
unet unexpected: ['scaled_fp8']
Requested to load PulidFluxModel
loaded completely; 95367431640625005117571072.00 MB usable, 1085.10 MB loaded, full load: True
Requested to load Flux
loaded partially; 8484.78 MB usable, 8376.65 MB loaded, 2976.38 MB offloaded, 108.02 MB buffer reserved, lowvram patches: 0
100%|██████████| 30/30 [02:01<00:00,  4.04s/it]
Requested to load AutoencodingEngine
Unloaded partially: 4089.86 MB freed, 4286.79 MB remains loaded, 162.11 MB buffer reserved, lowvram patches: 0
loaded completely; 855.80 MB usable, 159.87 MB loaded, full load: True
Prompt executed in 256.18 seconds

-----

[On success-the second time]

got prompt 11:03:27
loaded partially; 8480.79 MB usable, 8372.35 MB loaded, 2980.68 MB offloaded, 108.02 MB buffer reserved, lowvram patches: 0
100%|██████████| 30/30 [02:00<00:00,  4.00s/it]
Requested to load AutoencodingEngine
Unloaded partially: 4085.55 MB freed, 4286.79 MB remains loaded, 162.11 MB buffer reserved, lowvram patches: 0
loaded completely; 853.80 MB usable, 159.87 MB loaded, full load: True
Prompt executed in 167.23 seconds

[WK-Flux1-20251208-01.json](https://github.com/user-attachments/files/24022866/WK-Flux1-20251208-01.json)

**Comment by ghostsquad** [comment]
I'm running into this problem as well. Definitely not stale. Stalebots suck.

**Comment by stuttlepress** [comment]
This is an ongoing problem that can only be solved with --disable-pinned-memory.

Recent silence on the issue doesn't indicate it has gone away. We're waiting patiently for you to fix it. Don't sweep it under the rug, please.

**Comment by Kosinkadink** [comment]
For anyone still experiencing the issue, could you lost out your hardware setup, operating system, version of ComfyUI (if you know how to get the exact commit, that would be fantastic), as well as a simple workflow that lets you reproduce the issue on your machine? Ideally, could you also use the --disable-all-custom-nodes startup argument when replicating the issue?

We might be in the edge case territory here where any information as obscure as it may seem might be useful. Thank you!

**Comment by stuttlepress** [comment]
- 5090 GPU
- 128GB RAM
- Windows 11
- CUDA 13.1
- torch 2.9.1
- python 3.13.11

```
commit 469dd9c16ad88765ffe4e7bfa57dd80faafbaddf (HEAD -> master)
Author: nomadoor <124905471+nomadoor@users.noreply.github.com>
Date:   Wed Jan 14 09:48:10 2026 +0900
```
I updated ComfyUI via `git pull` earlier today. Experienced the error a few hours later. After updates, I run without `--disable-pinned-memory` with a heart full of optimism, but so far I am always eventually disappointed. :(

I can't reproduce the error at will. It occurs after ComfyUI has been running awhile. I frequently run batches of Qwen Image Edit or Wan FLF2V jobs, and often a job in the batch will fail if I don't have `--disable-pinned-memory` set.  
The workflows are not highly sophisticated, but they do use some custom nodes. I'll see if I can trigger the error with a batch of native workflows. If I can, I'll post back here.

**Comment by stuttlepress** [comment]
Well, I guess I can't do it with someone watching.

I ran a few batches of native workflows overnight with custom nodes disabled and pinned memory enabled. I haven't been able to reproduce the crash this way. 

Running ComfyUI with custom nodes enabled and without `--disable-pinned-memory`, I'll encounter this crash within an hour.  
With `--disable-pinned-memory` it's solid as a rock. No crashes ever.

In case it's useful, here's the session log from a recent crash.

[comfyui.prev.log](https://github.com/user-attachments/files/24711390/comfyui.prev.log)

**Comment by uio8898998-commits** [comment]
I encountered this issue as well
GPU 5070ti
RAM 32GB
Windows 11
CUDA 13.0
torch 2.9.1
python 3.13.9
commits ComfyUI: v0.9.2-15-g1a72bf20 (2026-01-18)Manager: V3.39.2
The error occurs when I switch workflow after generation, say I generated a video using ltx2 workflow and I want to generate an image with z-image, when I switched to z-image, it will fail and produce this error, and before this error occurs another message will spam my console :"Tried to unpin tensor not pinned by ComfyUI" a dozen times.

**Comment by SJTAYLOR001** [comment]
GPU: RTX 5090
Windows 11
Total VRAM 32607 MB, total RAM 130265 MB
pytorch version: 2.9.1+cu130
Python version: 3.13.9 (tags/v3.13.9:8183fa5, Oct 14 2025, 14:09:13) [MSC v.1944 64 bit (AMD64)]
ComfyUI version: 0.9.2
ComfyUI frontend version: 1.36.14
[ComfyUI-Easy-Use] server: v1.3.6 Loaded
### Loading: ComfyUI-Manager (V3.39.2)



Just reinstalled comfyuiPortable today 19th Jan 2026, as installing a custom node set has killed my last version.

**Comment by monstari** [comment]
Is this pinned memory issue just happening with the blackwell cards?

**Comment by ooofest** [comment]
Piling on with another example.

Windows 10, 64GB RAM
RTX-3090 (24GB VRAM)

I did an "Update All" yesterday via the Manager - the prior update was a few weeks ago - and now previously working Wan 2.2 I2V and T2V workflows are eventually dying with the same message that started this topic.

<img width="965" height="589" alt="Image" src="https://github.com/user-attachments/assets/c879c0e7-ff47-4075-b813-304f25d59900" />

It's more easily repeatable on the three-KSampler workflows: either the first High Sampler dies immediately or that first High sampler node completes processing and then the error pops up just as the second High sampler node is started.  This occurs with either safetensors or GGUF base models.

After this error crops up, attempts to re-run workflows or generate other Wan workflows often result in empty/black or corrupted outputs from one or more samplers.

If I restart ComfyUI, the above corruptions are gone, at least until the next point that the CUDA error occurs.

Also, if I add:

`--disable-pinned-memory`

to my ComfyUI startup parameters and restart, these problems do not occur.

**Comment by wronglatitude** [comment]
I'm also having the same issue when using PuLiD flux II, If I bypass those nodes after a restart it runs with no issues, with PuliD enable I might get 1 generation before the error, or I might get 20.

**Comment by jkulius** [comment]
I am having the same issue, on Windows and Ubuntu 24.10, with z-image an LTXv2 workflows, different versions of pytorch, xformers, etc. Latest comfyui-GGUF version used, but occurs also without GGUF node in active workflow.

**Comment by 5andysalive** [comment]
i had this problem today for the first time, but now i have it a lot - but not always. A wan2.2 dasiva+svi pro run went through 8 chunks without problem. Then suddenly that error on every new run. 
Before i had it for the first time i did a manager restart after installing the  tts audio suite nodes. Maybe coincidence but i never saw that error before.   TTS and most other workflows  run without that error though  It feels kinda random.
